
export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SET_FACEBOOK_ACCOUNTS = 'SET_FACEBOOK_ACCOUNTS';
